IF
  StateCheck(TenthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(TenthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(NinthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(NinthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(EighthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(EighthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(SeventhNearestEnemyOf(Myself),STATE_HELPLESS)
  See(SeventhNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Allegiance(LastSeenBy(Myself),ENEMY)
  StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #10
    EquipMostDamagingMelee()
    MoveToObject(LastSeenBy(Myself))
    AttackReevaluate(LastSeenBy(Myself),15)
  RESPONSE #90
    Continue()
END

IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

