IF
	Global("EnteredBaldursGate","GLOBAL",0)
	Global("BANDIT_MOVIE","AR1900",0)
	Global("EnteredElderCity","GLOBAL",0)
	Global("StartCredits","AR0125",0)
	Global("EnteredArmInn","GLOBAL",0)
	Global("EnteredWreck","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredBaldursGate","GLOBAL",1)
		SetGlobal("BANDIT_MOVIE","AR1900",1)
		SetGlobal("EnteredElderCity","GLOBAL",1)
		SetGlobal("StartCredits","AR0125",1)
		SetGlobal("EnteredArmInn","GLOBAL",1)
		SetGlobal("EnteredWreck","GLOBAL",1)
END